### PR TITLE
added gtags events to buttons tabs anchors

### PR DESCRIPTION
**Pull request by ddfridley**
added gtags to events on buttons tabs and anchors on the /companies page. 
This is running on democracy-lab-dev.herokuapp.com and sending data to a new google analytics property by that name. 
It's a one file change on top of the iframes branch that is being tested. I'm hoping this can be merged in before the next push to production so we can start gathering data from the /companies page

### CODE REVIEW

**Comment by ddfridley** [comment]
The one file changed is https://github.com/DemocracyLab/CivicTechExchange/pull/1041/files#diff-9d6d406765860a07f141d7a0f21eba209040ae0b4193e4dc3810818083c1abbe

**Review by PeterBreen — CHANGES_REQUESTED** [review]
There's a great deal of iframe code in this PR, please clean that out and keep it in #984. I'm aware this was done so you could test still-unmerged code on dev, which is fine, but the PR is solely for gtags, so it should only have gtag changes.  

Second, I see the gtag event per tab on the Companies page, but I don't see any actual events being fired on click - certainly my network activity shows nothing heading to google, but that may be local to me. Have you been able to verify they're firing correctly and sending to google, using https://tagassistant.google.com or similar?

**Comment by ddfridley** [comment]
Yes, I will revert the iframe branch out.
Yes, I did connect this up to google analytics and see the onclick events coming through. 
image
HackathonProspectus and SponsorProspectus are the two onClick events.

I have not tried https://tagassistant.google.com/ - I will check into that for future. I predict we will be doing more with gtags.

**Comment by ddfridley** [comment]
Ok. the iframe#978 merge has been reverted. Looks so much nicer with only one file changed!.

**Review by PeterBreen — APPROVED** [review]

**Comment by ddfridley** [comment]
I am closing this request because I created a different one from a new branch. https://github.com/DemocracyLab/CivicTechExchange/pull/1067

**Pull request closed without merging**
