### PR TITLE
fix ceewa30: LoginChange

### PR DESCRIPTION
**Pull request by ceewa30**

### CODE REVIEW

**Comment by ceewa30** [comment]
When a user goes to log in. "Looks Good" will appear below the entry boxes - fixed

**Review by marlonkeating — CHANGES_REQUESTED** [review]
Why was example.env removed?

**Comment by ceewa30** [comment]
i renamed the file in my local

Thank You
Sivakumar

**Comment by PeterBreen** [comment]
Closing due to age, #970

**Pull request closed without merging**
