### PR TITLE
Added urls for approving volunteers by owners when not logged in

### PR DESCRIPTION
**Pull request by rohitk18**
#718

### CODE REVIEW

**Review by marlonkeating — CHANGES_REQUESTED** [review]
I get an error message when trying to approve a volunteer when not logged in.

image

**Comment by marlonkeating** [comment]
You get redirected to an error page when logging in, instead of the Home page, with the following error on the backend:
django.urls.exceptions.NoReverseMatch: Reverse for 'Home' not found. 'Home' is not a valid view function or pattern name.

**Comment by marlonkeating** [comment]
When I try to log in from the home page, I get redirected back to https://democracy-lab-prod-mirror.herokuapp.comhome/, which is an invalid url.

**Comment by rohitk18** [comment]
@marlonkeating  Please check the latest commit and let me know if there is any loophole in the login process.

**Comment by marlonkeating** [comment]
When I try to approve when not logged in, I get to the login page successfully, but logging in gets me this:

image

**Comment by marlonkeating** [comment]
Closing for inactivity.

**Pull request closed without merging**
