### PR TITLE
Remove Heap code

### LINKED ISSUE #1048: Remove Heap code
DemocracyLab used to use Heap for analytics, but no longer - so all Heap-related code should be removed.

 - remove all instances/uses of of  [HEAP_ANALYTICS_ID](https://github.com/search?q=repo%3ADemocracyLab%2FCivicTechExchange+HEAP_ANALYTICS_ID&type=code)  
 - remove heapApi.js from 'common/components/utils'
 - remove all uses of the [metrics](https://github.com/search?q=repo%3ADemocracyLab%2FCivicTechExchange%20metrics.&type=code) utility functions in common/components/utils/metrics.js
 - remove common/components/utils/metrics.js

Then, test the website to make sure it still renders all pages (smoke test). If the site renders all pages, no heap-related errors are in console, then this is done.

Note for code reviewer: After this code is deployed, remove the HEAP_ANALYTICS_ID key on the server, prod and all test environments.

### PR DESCRIPTION
**Pull request by sp6370**
FIX #1048
This pull request remove usage of Heap Analytics and disables website metric collection temporarily.

### CODE REVIEW

**Comment by sp6370** [comment]
@PeterBreen I am unable to assign reviewers to pull request. Could you please add yourself as the reviewer. 
Also, this my first pull request to CivicTechExchange, do let me know if I should change anything.

**Review by PeterBreen — CHANGES_REQUESTED** [review]
There's one remaining heap item I missed in the issue, here: 
https://github.com/DemocracyLab/CivicTechExchange/blob/2693a0b489a0284415cc1527392d80cd56661f73/common/components/controllers/MainController.jsx#L10

Please remove that line from MainController.

Also, could you make this PR a branch of democracylab's repo instead of from your fork of the repo? That is, instead of `sp6370:master` it'd be `DemocracyLab/a-branch-name-here`

**Comment by sp6370** [comment]
@PeterBreen I am unable to create a branch on DemocracyLab. Could you give me the required access?

**Comment by PeterBreen** [comment]
You should have access now, let me know if it doesn't work.

**Pull request closed without merging**
